name: Bug Report - My Minecraft Mod
description: Report a bug in My Minecraft Mod
title: "[Bug]: "
labels:
  - bug
  - forge-mod
  - 1.20.1
projects:
  - your-org/your-project
assignees:
  - your-username
body:
  - type: markdown
    attributes:
      value: |
        **Please fill out the following information when reporting a bug in My Minecraft Mod.**

        - **Mod Version:** 1.20.1
        - **Forge Version:** (e.g., 1.16.5, 1.17.1)
        - **Minecraft Version:** (e.g., 1.17.1)
        - **Issue Description:**
        - **Steps to Reproduce:**
        - **Expected Behavior:**
        - **Actual Behavior:**

        _Thank you for helping us improve My Minecraft Mod!_

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue you encountered.
      placeholder: Please be as detailed as possible.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: Include any relevant details or commands.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Please provide your expectations.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: Explain what occurred.

  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      description: Specify the Forge version you are using.
      placeholder: e.g., 1.16.5

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: Specify the Minecraft version you are using.
      placeholder: e.g., 1.17.1
