blank_issues_enabled: false
contact_links:
  - name: EpicTeyvat Discord
    url: https://discord.gg/rCRTBVzaV2
    about: "Please ask and answer questions here. Github issues aren't for questions. Huge props to the FTB team for making these ISSUE_TEMPLATEs!"